[package]
name = "register_macro_derive_and_attr"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
confy = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
darling = "0.20.10"
sqids = { workspace = true }
regex = { workspace = true }

[lib]
proc-macro = true
