[package]
name = "kc-api"
version.workspace = true
edition.workspace = true

[dependencies]
kc-api-interface = { workspace = true }
kc-api-interface-adapter = { workspace = true }
kc-api-database = { workspace = true }
kc-api-dto = { workspace = true }
kc-api-parser = { workspace = true }

[features]
default = ["graphviz", "from20250627"]
graphviz = ["kc-api-interface/graphviz", "kc-api-dto/graphviz"]
cytoscape = ["kc-api-interface/cytoscape", "kc-api-dto/cytoscape"]
from20250627 = ["kc-api-interface/from20250627", "kc-api-dto/from20250627"]
20250627 = ["kc-api-interface/20250627", "kc-api-dto/20250627"]
