[package]
name = "kc-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kc-api-interface = { workspace = true }
kc-api-interface-adapter = { workspace = true }
kc-api-database = { workspace = true }
kc-api-dto = { workspace = true }
kc-api-parser = { workspace = true }
kc-fleet-snapshot = { workspace = true }

[features]
default = ["graphviz", "from20250627", "schema_v1"]
graphviz = [
    "kc-api-database/graphviz",
    "kc-api-dto/graphviz",
]
cytoscape = [
    "kc-api-database/cytoscape",
    "kc-api-dto/cytoscape",
]
from20250627 = [
    "kc-api-interface/from20250627",
    "kc-api-interface-adapter/from20250627",
    "kc-api-dto/from20250627",
]
20250627 = [
    "kc-api-interface/20250627",
    "kc-api-interface-adapter/20250627",
    "kc-api-dto/20250627",
]
schema_v1 = ["kc-api-database/schema_v1"]
schema_v2 = ["kc-api-database/schema_v2"]
