[package]
name = "register_trait"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
register_macro_derive_and_attr = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
