[package]
name = "kc-api-parser"
version.workspace = true
edition.workspace = true

[dependencies]
kc-api-interface = { path = "../kc-api-interface" }
kc-api-dto = { path = "../kc-api-dto" }
register_trait = { workspace = true }
serde_json = { workspace = true }
serde_qs = { workspace = true }
tracing = { workspace = true }
