[package]
name = "kc-api-interface-adapter"
version.workspace = true
edition.workspace = true

[dependencies]
chrono = { workspace = true }
once_cell = { workspace = true }
register_trait = { workspace = true }
serde = { workspace = true }
ts-rs = { workspace = true }
apache-avro = { workspace = true }
kc-api-interface = { path = "../kc-api-interface" }
kc-api-dto = { path = "../kc-api-dto" }

[features]
default = [ "graphviz", "from20250627" ]
graphviz = []
cytoscape = []

from20250627 = ["20250627"]
20250627 = []
