[package]
name = "kc-api-interface-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono = { workspace = true }
once_cell = { workspace = true }
register_trait = { workspace = true }
serde = { workspace = true }
ts-rs = { workspace = true }
apache-avro = { workspace = true }
kc-api-interface = { workspace = true }
kc-api-dto = { workspace = true }

[features]
default = [ "from20250627" ]

from20250627 = ["20250627"]
20250627 = []
