[workspace]
members = [
	"crates/kc-api",
	"crates/kc-api-interface",
	"crates/kc-api-interface-adapter",
	"crates/kc-api-database",
	"crates/kc-api-dto",
	"crates/kc-api-parser",
	"crates/register_trait",
	"crates/register_macro_derive_and_attr",
	"crates/kc-api-integration-test", "crates/kc-fleet-snapshot",
]
resolver = "2"

[workspace.package]
name = "kc_api"
version = "0.3.1"
edition = "2021"

[workspace.dependencies]
apache-avro = { version = "0.17.0", features = ["derive", "zstandard"] }
chrono = "0.4.38"
confy = "0.6.1"
dot-writer = "0.1.3"
dotenvy = "0.15.7"
dotenvy_macro = "0.15.7"
once_cell = "1.21.3"
proc-macro2 = "1.0.86"
quote = "1.0.38"
register_macro_derive_and_attr = { path = "crates/register_macro_derive_and_attr" }
register_trait = { path = "crates/register_trait" }
kc-api-database = { path = "crates/kc-api-database" }
kc-api-interface = { path = "crates/kc-api-interface" }
kc-api-dto = { path = "crates/kc-api-dto" }
kc-api-parser = { path = "crates/kc-api-parser" }
kc-api-interface-adapter = { path = "crates/kc-api-interface-adapter" }
regex = "1.10.6"
sqids = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_qs = "0.14.0"
syn = { version = "2.0.67", features = ["full"] }
tracing = "0.1.41"
tracing-unwrap = "1.0.1"
ts-rs = "11.0.1"
uuid = { version = "1.16.0", features = ["v4", "v7"] }

[profile.dev]
codegen-units = 1024
