# This file is used to configure the FUSOU-PROXY and FUSOU-APP
# By default, the application's features are kept to a minimum. To use restricted features, please change the configuration values.

[proxy]
# Whether to save KanColle API requests
allow_save_api_requests = true

# Whether to save KanColle API responses
allow_save_api_responses = true

# Whether to save KanColle resources such as images and metadata
allow_save_resources = true

# The location to save files
# The default location is under the user's Documents directory
# to use the default location, leave this empty
save_file_location = ""

    [proxy.network]    
    # The backend crate used in FUSOU-PROXY
    # You can choose two backend crates
    # 1. hudsucker          (default)         (https://crates.io/crates/hudsucker)
    # 2. http-mitm-proxy    (not implemented) (https://crates.io/crates/http-mitm-proxy)
    backend_crate = "hudsucker"

    # Whether to enforce HTTP to proxy client
    # default is false
    enforce_http = false

    # Whether to set TCP_NODELAY on the proxy server
    # default is false
    set_nodelay = false

    # The timeout (in seconds) for connecting to the KanColle server
    # set 0 or negative to use the system default
    connect_timeout = 0

    # The interval (in seconds) to keep the TCP connection alive
    # set 0 or negative to use the system default
    keepalive_interval = 0

    # The size of the receive buffer
    # set 0 or negative to use the system default
    recv_buffer_size = 8_000_000

    # The size of the send buffer
    # set 0 or negative to use the system default
    send_buffer_size = 8_000_000

    # The fixed port of the proxy server
    # set 0 to use an unused port automatically
    proxy_server_port = 0


    [proxy.certificates]
    # Whether to use generated certificates
    # default is true
    use_generated_certs = true

    # The path to the SSL certificate file
    # this option is only used when `use_generated_certs` is false
    cert_file = "path/to/cert/file"

    # The path to the SSL key file
    # this option is only used when `use_generated_certs` is false
    key_file = "path/to/key/file"


    [proxy.pac]
    # Whether to use a custom PAC script
    # default is false
    use_custom_pac = false

    # The path to the PAC script
    # this option is only used when `use_custom_pac` is true
    pac_script = "path/to/pac/script.pac"

    # The fixed port of the PAC server
    # set 0 to use an unused port automatically
    pac_server_port = 0


[app]
    [app.connect_kc_server]
    # The hostname of the KanColle server you want to connect to
    # This is the hostname or IP address of the server, like w16s.kancolle-server.com
    # The correspondence table of server hostname and server name is as follows
    #
    #  No. | server hostname          | server name
    # ---------------------------------------------------
    #   1  | w01y.kancolle-server.com | 横須賀鎮守府
    #   2  | w02k.kancolle-server.com | 新呉鎮守府
    #   3  | w03s.kancolle-server.com | 佐世保鎮守府
    #   4  | w04m.kancolle-server.com | 舞鶴鎮守府
    #   5  | w05o.kancolle-server.com | 大湊警備府
    #   6  | w06k.kancolle-server.com | トラック泊地
    #   7  | w07l.kancolle-server.com | リンガ泊地
    #   8  | w08r.kancolle-server.com | ラバウル基地
    #   9  | w09s.kancolle-server.com | ショートランド泊地
    #  10  | w10b.kancolle-server.com | ブイン基地
    #  11  | w11t.kancolle-server.com | タウイタウイ泊地
    #  12  | w12p.kancolle-server.com | パラオ泊地
    #  13  | w13b.kancolle-server.com | ブルネイ泊地
    #  14  | w14h.kancolle-server.com | 単冠湾泊地
    #  15  | w15p.kancolle-server.com | 幌筵泊地
    #  16  | w16s.kancolle-server.com | 宿毛湾泊地
    #  17  | w17k.kancolle-server.com | 鹿屋基地
    #  18  | w18i.kancolle-server.com | 岩川基地
    #  19  | w19s.kancolle-server.com | 佐伯湾泊地
    #  20  | w20h.kancolle-server.com | 柱島泊地
    #
    # Set KanColle server hostname or empty if you want to choose KanColle server automatically
    # kc_server_name = "w16s.kancolle-server.com" # This is example
    kc_server_name = "w16s.kancolle-server.com"


    [app.browser]
    # The URL to open first in the browser
    url = "http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/"


    [app.autostart]
    # Whether to enable the Tauri autostart integration
    # default is false
    enable = false


    [app.theme]
    # The theme to use for the application
    # you can choose between "light" and "dark"
    theme = "light"


    [app.font]
    # The font family to use for the application
    # you can choose any font family in Google Fonts
    # keep it empty to use the default font
    font_family = "Noto Sans JP"


    [app.discord]
    # Whether to enable Discord integration (Discord Rich Presence)
    enable_discord_integration = true

    # Whether to use a custom to use for Discord Rich Presence
    use_custom_message = true

    # The custom message to use for Discord Rich Presence
    # This option is only used when `use_custom_message` is true
    custom_message = "This is experimental implementation"
    custom_details = "Playing KanColle with FUSOU"

    # Whether to use a custom image for Discord Rich Presence
    use_custom_image = true

    # The custom image url to use for Discord Rich Presence
    # This option is only used when `use_custom_image` is true
    custom_image_url = "https://avatars.githubusercontent.com/u/68815462?v=4"


    [app.database]
    # Whether to save KanColle data to the cloud
    # this feature can be enabled with user authentication
    # check [app.auth]
    allow_data_to_cloud = true
    # Whether to save KanColle data to the local filesystem
    allow_data_to_local = true


    [app.database.google_drive]
    # The size of table user can get from Google Drive at once
    # this option is only used when [app.database] is enabled
    page_size = 100

    # The interval (in cron format) to sync data to Google Drive
    # this option is only used when [app.database] is enabled
    schedule_cron = "0 0 * * * *" # every hour


    [app.database.local]
    # Base directory used when writing KanColle data locally
    # leave it empty to use the Documents directory/FUSOU/storage path
    output_directory = ""


    [app.auth]
    # Whether to deny user authentication
    # To be careful because there is no method to reset the authentication state until the authentication expires
    deny_auth = false


    [app.kc_window]
    # The debounce time (in milliseconds) for window resize events
    # This option is used when you use linux platform and the system internally uses wayland instead of X11
    resize_debounce_millis = 200

    # The duration (in milliseconds) to keep the KanColle window size when resized events occur
    # This option is used when you use linux platform and the system internally uses wayland instead of X11
    keep_window_size_duration_millis = 1000

    # The maximum inner width and height of the KanColle window
    max_inner_width = 1920
    max_inner_height = 1080

    # The default inner width and height of the KanColle window
    # This size is used for keeping aspect ratio when resizing the window
    default_inner_width = 1200
    default_inner_height = 720

    # The height of the window title bar
    # This option is used when you use linux platform and the system internally uses wayland instead of X11
    window_title_bar_height = 68


[env]
# Environment-specific configurations
# Keep it empty for now