[package]
name = "configs"
version = "0.1.1"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.5"
once_cell = "1.21.3"
tracing = "0.1.41"
tracing-unwrap = "1.0.1"