[package]
name = "formula_miner"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.26.3"
crossterm = "0.27.0"
rand = "0.8.5"
anyhow = "1.0.86"
reqwest = { version = "0.11.24", features = ["blocking", "json"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.107"
uuid = { version = "1.10.0", features = ["serde", "v4"] }
ctrlc = "3.4"
chrono = { version = "0.4", features = ["serde"] }

